import { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { buildWeeklyPlan, loadMealSwaps, loadProfile, saveMealSwaps, saveProfile, type MealFrequency, type MealSwap, type UserProfile } from "@/lib/rootedfit-profile";

const FREQUENCIES: { value: MealFrequency; label: string; description: string }[] = [
  { value: "one_plus_snack", label: "One main meal + snack ideas", description: "One full recipe and two snack ideas each day." },
  { value: "two", label: "Two meals + snack ideas", description: "Two recipe slots each day, plus optional snack ideas." },
  { value: "three", label: "Three meals + snack ideas", description: "Breakfast, lunch, and dinner recipe slots." },
];

export default function MealsScreen() {
  const [profile, setProfile] = useState<UserProfile | null>(null);
  const [swaps, setSwaps] = useState<MealSwap[]>([]);
  const [dayIndex, setDayIndex] = useState(0);
  useEffect(() => { loadProfile().then(setProfile); loadMealSwaps().then(setSwaps); }, []);
  const plan = useMemo(() => profile ? buildWeeklyPlan(profile) : null, [profile]);
  const day = plan?.dailyMeals[dayIndex];

  const setFrequency = async (mealFrequency: MealFrequency) => { if (!profile) return; const next = { ...profile, mealFrequency }; setProfile(next); await saveProfile(next); };
  const recipeFor = (slotKey: string, fallback: NonNullable<typeof plan>["meals"][number]) => { const replacement = swaps.find((swap) => swap.slotKey === slotKey); return replacement && plan ? plan.meals[replacement.recipeIndex % plan.meals.length] : fallback; };
  const swapRecipe = async (slotKey: string, title: string) => { if (!plan) return; const existing = swaps.find((swap) => swap.slotKey === slotKey)?.recipeIndex ?? Math.max(0, plan.meals.findIndex((meal) => meal.title === title)); const next = [...swaps.filter((swap) => swap.slotKey !== slotKey), { slotKey, recipeIndex: (existing + 1) % plan.meals.length }]; setSwaps(next); await saveMealSwaps(next); };

  if (!profile || !plan || !day) return <ScreenContainer edges={["top", "bottom", "left", "right"]} style={styles.loading}><ActivityIndicator color="#2D6A4F" /></ScreenContainer>;
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} style={styles.screen}><ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>MEALS</Text><Text style={styles.title}>Full recipes and your real grocery list.</Text><Text style={styles.body}>Set the rhythm that fits you, open every recipe, and swap anything you do not want.</Text><View style={styles.choiceStack}>{FREQUENCIES.map((item) => <Pressable key={item.value} onPress={() => setFrequency(item.value)} style={[styles.choice, profile.mealFrequency === item.value && styles.choiceActive]}><Text style={styles.choiceTitle}>{profile.mealFrequency === item.value ? "✓ " : ""}{item.label}</Text><Text style={styles.choiceCopy}>{item.description}</Text></Pressable>)}</View><Text style={styles.sectionTitle}>Recipes for your week</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{plan.dailyMeals.map((item, index) => <Pressable key={item.label} onPress={() => setDayIndex(index)} style={[styles.chip, dayIndex === index && styles.chipActive]}><Text style={[styles.chipText, dayIndex === index && styles.chipTextActive]}>{item.label}</Text></Pressable>)}</ScrollView><View style={styles.card}><Text style={styles.kicker}>{day.label.toUpperCase()} · {day.slots.length} PLANNED {day.slots.length === 1 ? "MEAL" : "MEALS"}</Text>{day.slots.map((slot) => { const key = `${day.day}-${slot.label}`; const recipe = recipeFor(key, slot.meal); return <View key={slot.label} style={styles.slot}><Text style={styles.slotLabel}>{slot.label}</Text><Text style={styles.recipeTitle}>{recipe.title}</Text><Text style={styles.ingredients}>Ingredients: {recipe.ingredients.join(" · ")}</Text><Pressable onPress={() => swapRecipe(key, recipe.title)} style={styles.swap}><Text style={styles.swapText}>Swap this meal →</Text></Pressable><Text style={styles.methodTitle}>How to make it</Text>{recipe.steps.map((step, index) => <Text key={step} style={styles.method}>{index + 1}. {step}</Text>)}<Text style={styles.note}>{recipe.equipmentNote}</Text><Text style={styles.drink}>Drink idea: {recipe.drink}</Text></View>; })}{day.snackIdeas.length ? <View style={styles.snacks}><Text style={styles.slotLabel}>Optional snack ideas</Text>{day.snackIdeas.map((idea) => <Text key={idea} style={styles.method}>• {idea}</Text>)}</View> : null}</View><View style={styles.card}><Text style={styles.kicker}>GROCERY LIST FROM THIS WEEK’S RECIPES</Text>{plan.shoppingGroups.map((group) => <View key={group.title} style={styles.groceryGroup}><Text style={styles.groceryTitle}>{group.title}</Text>{group.items.map((item) => <Text key={item} style={styles.method}>□ {item}</Text>)}</View>)}</View></ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({
  screen: { backgroundColor: "#F8F6EF" }, loading: { alignItems: "center", backgroundColor: "#F8F6EF", justifyContent: "center" }, content: { padding: 22 }, eyebrow: { color: "#2D6A4F", fontSize: 11, fontWeight: "800", letterSpacing: 1.2, marginBottom: 10 }, title: { color: "#1F2A25", fontSize: 29, fontWeight: "800", lineHeight: 36 }, body: { color: "#526259", fontSize: 16, lineHeight: 24, marginBottom: 20, marginTop: 9 }, choiceStack: { gap: 9, marginBottom: 23 }, choice: { backgroundColor: "#FFFFFF", borderColor: "#DDE5DA", borderRadius: 15, borderWidth: 1, padding: 15 }, choiceActive: { backgroundColor: "#EAF3EA", borderColor: "#2D6A4F" }, choiceTitle: { color: "#1F2A25", fontSize: 15, fontWeight: "800" }, choiceCopy: { color: "#6B7A70", fontSize: 13, lineHeight: 19, marginTop: 4 }, sectionTitle: { color: "#1F2A25", fontSize: 20, fontWeight: "800", marginBottom: 11 }, chips: { gap: 8, marginBottom: 15 }, chip: { backgroundColor: "#FFFFFF", borderColor: "#DDE5DA", borderRadius: 13, borderWidth: 1, paddingHorizontal: 14, paddingVertical: 9 }, chipActive: { backgroundColor: "#2D6A4F", borderColor: "#2D6A4F" }, chipText: { color: "#385046", fontSize: 13, fontWeight: "800" }, chipTextActive: { color: "#FFFFFF" }, card: { backgroundColor: "#FFFFFF", borderColor: "#DDE5DA", borderRadius: 18, borderWidth: 1, marginBottom: 16, padding: 17 }, kicker: { color: "#2D6A4F", fontSize: 10, fontWeight: "800", letterSpacing: 1, marginBottom: 9 }, slot: { borderTopColor: "#E5EBE3", borderTopWidth: 1, paddingVertical: 13 }, slotLabel: { color: "#2D6A4F", fontSize: 11, fontWeight: "800", letterSpacing: 0.8, marginBottom: 5 }, recipeTitle: { color: "#1F2A25", fontSize: 18, fontWeight: "800", lineHeight: 24 }, ingredients: { color: "#526259", fontSize: 13, lineHeight: 20, marginTop: 6 }, swap: { alignSelf: "flex-start", backgroundColor: "#EAF3EA", borderRadius: 10, marginTop: 10, paddingHorizontal: 12, paddingVertical: 9 }, swapText: { color: "#1D583E", fontSize: 13, fontWeight: "800", textDecorationLine: "underline" }, methodTitle: { color: "#1F2A25", fontSize: 14, fontWeight: "800", marginTop: 12 }, method: { color: "#405247", fontSize: 13, lineHeight: 20, marginTop: 5 }, note: { color: "#6B7A70", fontSize: 13, lineHeight: 19, marginTop: 10 }, drink: { color: "#2D6A4F", fontSize: 13, fontWeight: "800", lineHeight: 19, marginTop: 8 }, snacks: { backgroundColor: "#F1F7F0", borderRadius: 12, marginTop: 4, padding: 13 }, groceryGroup: { borderTopColor: "#E5EBE3", borderTopWidth: 1, paddingVertical: 11 }, groceryTitle: { color: "#1F2A25", fontSize: 15, fontWeight: "800", marginBottom: 4 },
});
