import { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import * as WebBrowser from "expo-web-browser";

import { ScreenContainer } from "@/components/screen-container";
import { CompletionRatingPrompt } from "@/components/completion-rating-prompt";
import { useAuth } from "@/hooks/use-auth";
import { buildWeeklyPlan, loadExerciseLogs, loadProfile, loadWorkoutSessionStates, saveExerciseLogs, saveWorkoutSessionStates, type LocalExerciseLog, type UserProfile, type WorkoutSessionState } from "@/lib/rootedfit-profile";
import { trpc } from "@/lib/trpc";

type WorkoutResource = { title: string; duration: string; format: string; why: string; url: string };

const LIBRARY: Record<string, WorkoutResource[]> = {
  weight_loss: [{ title: "30 Min Low Impact Home Workout", duration: "30 min", format: "Low-impact cardio", why: "A follow-along option for people who prefer a no-jumping home session.", url: "https://www.youtube.com/watch?v=MOz41fYRBvs" }, { title: "20-Minute Bodyweight Workout for Beginners", duration: "20 min", format: "Bodyweight strength", why: "A compact no-equipment session to build a repeatable movement habit.", url: "https://www.youtube.com/watch?v=C7-xW9mRNiI" }],
  weight_gain: [{ title: "20 Min Full Body Toning & Strength", duration: "20 min", format: "At-home strength", why: "A strength-focused option for users who have weights or filled bottles available.", url: "https://www.youtube.com/watch?v=YYgYRSkFoJs" }, { title: "20-Minute Bodyweight Workout for Beginners", duration: "20 min", format: "Bodyweight strength", why: "A practical foundation when equipment is limited.", url: "https://www.youtube.com/watch?v=C7-xW9mRNiI" }],
  toning: [{ title: "20 Min Full Body Toning & Strength", duration: "20 min", format: "At-home strength", why: "A follow-along strength session; use weights, bottles, or bodyweight as appropriate.", url: "https://www.youtube.com/watch?v=YYgYRSkFoJs" }, { title: "30 Min Full Body Pilates", duration: "30 min", format: "Pilates", why: "A controlled, no-equipment option for home movement variety.", url: "https://www.youtube.com/watch?v=U5LwQW_IQOc" }],
  core_mobility: [{ title: "30 Min Full Body Pilates", duration: "30 min", format: "Pilates", why: "A mat-free or mat-optional controlled movement session.", url: "https://www.youtube.com/watch?v=U5LwQW_IQOc" }, { title: "Beginner Yoga", duration: "20–30 min", format: "Yoga and mobility", why: "A gentler follow-along option for a low-intensity day.", url: "https://www.youtube.com/watch?v=AB3Y-4a3ZrU" }],
  energy: [{ title: "Beginner Yoga", duration: "20–30 min", format: "Yoga and mobility", why: "A gentle movement break when you want to reset rather than push intensity.", url: "https://www.youtube.com/watch?v=AB3Y-4a3ZrU" }, { title: "20-Minute Bodyweight Workout for Beginners", duration: "20 min", format: "Bodyweight", why: "A short, simple option for days when energy is better later in the day.", url: "https://www.youtube.com/watch?v=C7-xW9mRNiI" }],
  consistency: [{ title: "20-Minute Bodyweight Workout for Beginners", duration: "20 min", format: "No equipment", why: "A manageable starting point for keeping a movement routine realistic.", url: "https://www.youtube.com/watch?v=C7-xW9mRNiI" }, { title: "Beginner Yoga", duration: "20–30 min", format: "Mobility", why: "A low-pressure option for recovery or restart days.", url: "https://www.youtube.com/watch?v=AB3Y-4a3ZrU" }],
  body_composition: [{ title: "30 Min Low Impact Home Workout", duration: "30 min", format: "Low-impact cardio", why: "A home option that can sit alongside food and movement consistency habits.", url: "https://www.youtube.com/watch?v=MOz41fYRBvs" }, { title: "20 Min Full Body Toning & Strength", duration: "20 min", format: "At-home strength", why: "A strength-based complement when the equipment and energy are available.", url: "https://www.youtube.com/watch?v=YYgYRSkFoJs" }],
};

const TITLE: Record<string, string> = { weight_loss: "Weight-loss focus", weight_gain: "Weight-gain focus", toning: "Strength & toning focus", core_mobility: "Core & mobility focus", energy: "Energy focus", consistency: "Consistency focus", body_composition: "Body-composition habits" };

export default function WorkoutsScreen() {
  const [profile, setProfile] = useState<UserProfile | null>(null);
  const [states, setStates] = useState<WorkoutSessionState[]>([]);
  const [exerciseLogs, setExerciseLogs] = useState<LocalExerciseLog[]>([]);
  const [activeWorkout, setActiveWorkout] = useState<{ id: string; title: string } | null>(null);
  const [exerciseName, setExerciseName] = useState("");
  const [setNumber, setSetNumber] = useState("1");
  const [repCount, setRepCount] = useState("");
  const [weightUsedKg, setWeightUsedKg] = useState("");
  const [completedWorkout, setCompletedWorkout] = useState<{ id: string; title: string } | null>(null);
  const { isAuthenticated } = useAuth();
  const syncExerciseLog = trpc.exerciseLogs.create.useMutation();

  useEffect(() => { loadProfile().then(setProfile); loadWorkoutSessionStates().then(setStates); loadExerciseLogs().then(setExerciseLogs); }, []);
  if (!profile) return <ScreenContainer edges={["top", "bottom", "left", "right"]} style={styles.loading}><ActivityIndicator color="#2D6A4F" /></ScreenContainer>;
  const goal = profile.goal ?? "consistency";
  const weeklyPlan = useMemo(() => buildWeeklyPlan(profile), [profile]);
  const resources = weeklyPlan.workouts;
  const open = (url: string) => WebBrowser.openBrowserAsync(url, { controlsColor: "#2D6A4F", enableBarCollapsing: true, showTitle: true }).catch(() => Alert.alert("Workout link could not open", "Please check your internet connection and try again."));
  const updateState = async (workoutId: string, update: Partial<WorkoutSessionState>) => { const current = states.find((item) => item.workoutId === workoutId) ?? { workoutId, saved: false, completedAt: null }; const nextState = { ...current, ...update }; const next = [...states.filter((item) => item.workoutId !== workoutId), nextState]; setStates(next); await saveWorkoutSessionStates(next); };
  const markWorkoutComplete = async (workoutId: string, title: string, currentlyComplete: boolean) => { await updateState(workoutId, { completedAt: currentlyComplete ? null : new Date().toISOString().slice(0, 10) }); if (!currentlyComplete) setCompletedWorkout({ id: workoutId, title }); };
  const chooseWorkoutForLog = (workoutId: string, title: string) => { setActiveWorkout({ id: workoutId, title }); if (!exerciseName) setExerciseName("Bodyweight squat"); };
  const saveSetLog = async () => { const set = Math.floor(Number(setNumber)); const reps = Math.floor(Number(repCount)); const weight = Number(weightUsedKg); if (!activeWorkout || !exerciseName.trim() || !Number.isFinite(set) || set < 1 || !Number.isFinite(reps) || reps < 1) { Alert.alert("Add the set details", "Choose a workout, enter an exercise name, set number, and at least one repetition."); return; } const nextLog: LocalExerciseLog = { id: `${Date.now()}-${activeWorkout.id}`, workoutId: activeWorkout.id, exerciseName: exerciseName.trim(), setNumber: set, repCount: reps, weightUsedKg: weightUsedKg.trim() && Number.isFinite(weight) && weight >= 0 ? weight : null, loggedAt: new Date().toISOString() }; const next = [nextLog, ...exerciseLogs]; setExerciseLogs(next); await saveExerciseLogs(next); if (isAuthenticated) { try { await syncExerciseLog.mutateAsync({ workoutId: nextLog.workoutId, exerciseName: nextLog.exerciseName, setNumber: nextLog.setNumber, repCount: nextLog.repCount, weightUsedKg: nextLog.weightUsedKg }); } catch { /* Local record remains available if optional account sync is unavailable. */ } } setRepCount(""); setWeightUsedKg(""); setSetNumber(String(set + 1)); };

  return <ScreenContainer edges={["top", "bottom", "left", "right"]} style={styles.screen}><ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>YOUR SEVEN-DAY HOME WORKOUT PLAN</Text><Text style={styles.title}>{TITLE[goal]}</Text><Text style={styles.body}>Each day has a different at-home session shaped around your primary focus, time, space, and available equipment. Choose the listed day or use a different day when life shifts.</Text>{resources.map((item) => { const workoutId = `week-${profile.rotationWeek}-${item.day}-${item.title}`; const state = states.find((entry) => entry.workoutId === workoutId) ?? { workoutId, saved: false, completedAt: null }; return <View key={workoutId} style={[styles.card, state.completedAt && styles.cardComplete]}><Text style={styles.cardKicker}>{item.label.toUpperCase()} · {item.category.toUpperCase()} · {item.durationMinutes} MIN</Text><Text style={styles.cardTitle}>{item.title}</Text><Text style={styles.cardCopy}>{item.instructions.join(" ")}</Text><Text style={styles.cardCopy}>{item.adaptation}</Text>{state.completedAt ? <Text style={styles.completedNote}>Completed {state.completedAt}</Text> : null}<Pressable onPress={() => open(item.videoUrl)} style={styles.openButton}><Text style={styles.openButtonText}>Open {item.videoProvider} session →</Text></Pressable><View style={styles.actionRow}><Pressable onPress={() => updateState(workoutId, { saved: !state.saved })} style={[styles.actionButton, state.saved && styles.actionButtonActive]}><Text style={styles.actionButtonText}>{state.saved ? "★ Saved" : "☆ Save session"}</Text></Pressable><Pressable onPress={() => markWorkoutComplete(workoutId, item.title, Boolean(state.completedAt))} style={[styles.actionButton, state.completedAt && styles.actionButtonActive]}><Text style={styles.actionButtonText}>{state.completedAt ? "✓ Completed" : "Mark complete"}</Text></Pressable></View><Pressable onPress={() => chooseWorkoutForLog(workoutId, item.title)} style={styles.logButton}><Text style={styles.logButtonText}>{activeWorkout?.id === workoutId ? "Logging this session" : "Log a home set"}</Text></Pressable></View>; })}

    <View style={styles.logCard}><Text style={styles.cardKicker}>HOME EXERCISE LOG</Text><Text style={styles.cardTitle}>{activeWorkout ? activeWorkout.title : "Choose “Log a home set” above"}</Text><Text style={styles.cardCopy}>Record bodyweight or weighted home variations. Weight is optional and uses kilograms.</Text><TextInput value={exerciseName} onChangeText={setExerciseName} placeholder="Exercise name, e.g. bodyweight squat" placeholderTextColor="#93A197" style={styles.input} returnKeyType="done" /><View style={styles.inputRow}><TextInput value={setNumber} onChangeText={setSetNumber} placeholder="Set" placeholderTextColor="#93A197" keyboardType="number-pad" style={[styles.input, styles.inputHalf]} /><TextInput value={repCount} onChangeText={setRepCount} placeholder="Reps" placeholderTextColor="#93A197" keyboardType="number-pad" style={[styles.input, styles.inputHalf]} /></View><TextInput value={weightUsedKg} onChangeText={setWeightUsedKg} placeholder="Weight used in kg (optional; 0 for bodyweight)" placeholderTextColor="#93A197" keyboardType="decimal-pad" style={styles.input} /><Pressable onPress={saveSetLog} style={styles.logPrimary}><Text style={styles.logPrimaryText}>Save set locally</Text></Pressable>{exerciseLogs.slice(0, 5).map((log) => <Text key={log.id} style={styles.logHistory}>• {log.exerciseName} — set {log.setNumber}: {log.repCount} reps{log.weightUsedKg !== null ? ` · ${log.weightUsedKg} kg` : " · bodyweight"}</Text>)}</View>
    <View style={styles.note}><Text style={styles.noteText}>Saved and completed states, plus home set logs, remain on this device in the current MVP. When you are signed in, new set logs also try to sync to your RootedFit account; your kitchen, electricity, meal, and nutrition information remains unchanged. Pause, modify, or choose a gentler session if anything does not feel right.</Text></View></ScrollView><CompletionRatingPrompt visible={Boolean(completedWorkout)} completionKey={`workout:${completedWorkout?.id ?? ""}:${new Date().toISOString().slice(0, 10)}`} title={completedWorkout?.title ?? "this workout"} onClose={() => setCompletedWorkout(null)} /></ScreenContainer>;
}

const styles = StyleSheet.create({
  screen: { backgroundColor: "#F8F6EF" }, loading: { alignItems: "center", backgroundColor: "#F8F6EF", justifyContent: "center" }, content: { padding: 22 }, eyebrow: { color: "#2D6A4F", fontSize: 11, fontWeight: "800", letterSpacing: 1.2, marginBottom: 10 }, title: { color: "#1F2A25", fontSize: 30, fontWeight: "800", letterSpacing: -0.5, lineHeight: 36 }, body: { color: "#526259", fontSize: 16, lineHeight: 24, marginBottom: 20, marginTop: 10 }, card: { backgroundColor: "#FFFFFF", borderColor: "#DDE5DA", borderRadius: 18, borderWidth: 1, marginBottom: 13, padding: 17 }, cardComplete: { backgroundColor: "#F1F7F0", borderColor: "#9BC8A7" }, cardKicker: { color: "#2D6A4F", fontSize: 10, fontWeight: "800", letterSpacing: 1, marginBottom: 7 }, cardTitle: { color: "#1F2A25", fontSize: 19, fontWeight: "800", lineHeight: 25 }, cardCopy: { color: "#526259", fontSize: 14, lineHeight: 21, marginTop: 7 }, completedNote: { color: "#1D583E", fontSize: 13, fontWeight: "800", marginTop: 10 }, openButton: { alignItems: "center", backgroundColor: "#EAF3EA", borderRadius: 12, marginTop: 15, minHeight: 46, justifyContent: "center", paddingHorizontal: 12 }, openButtonText: { color: "#1D583E", fontSize: 14, fontWeight: "800", textDecorationLine: "underline" }, actionRow: { flexDirection: "row", gap: 9, marginTop: 10 }, actionButton: { alignItems: "center", borderColor: "#C9DFC9", borderRadius: 10, borderWidth: 1, flex: 1, minHeight: 40, justifyContent: "center", paddingHorizontal: 8 }, actionButtonActive: { backgroundColor: "#D8EADD", borderColor: "#2D6A4F" }, actionButtonText: { color: "#1D583E", fontSize: 12, fontWeight: "800" }, logButton: { alignItems: "center", borderColor: "#C9DFC9", borderRadius: 10, borderWidth: 1, marginTop: 10, paddingVertical: 10 }, logButtonText: { color: "#1D583E", fontSize: 13, fontWeight: "800" }, logCard: { backgroundColor: "#FFFFFF", borderColor: "#C9DFC9", borderRadius: 18, borderWidth: 1, marginBottom: 14, padding: 17 }, input: { backgroundColor: "#F8F9F5", borderColor: "#DDE5DA", borderRadius: 11, borderWidth: 1, color: "#1F2A25", fontSize: 14, marginTop: 10, minHeight: 45, paddingHorizontal: 12 }, inputRow: { flexDirection: "row", gap: 10 }, inputHalf: { flex: 1 }, logPrimary: { alignItems: "center", backgroundColor: "#2D6A4F", borderRadius: 12, marginTop: 11, paddingVertical: 13 }, logPrimaryText: { color: "#FFFFFF", fontSize: 14, fontWeight: "800" }, logHistory: { color: "#405247", fontSize: 13, lineHeight: 20, marginTop: 9 }, note: { backgroundColor: "#FCF3E7", borderColor: "#E8D1A4", borderRadius: 16, borderWidth: 1, marginTop: 5, padding: 15 }, noteText: { color: "#6B4A2C", fontSize: 13, lineHeight: 19 },
});
